### ISSUE TITLE
Send email notification when project status set to rejected, suspended or closed.

### ISSUE THREAD

**Issue by tystakartografen** [tystakartografen/cogs3#14]
**Description**
When a project is rejected, suspended or closed the project owner should be sent an email notification with a short explanation as to the decision. 

- Add a 'comment' field to the project model.

**Comment by rantahar** [comment]
If nobody minds, I will take a look sending the emails

**Comment by rantahar** [comment]
Pull request #42 adds adds a check for the status and sending the email in project.models.Project.save(). We also check that the email is sent in integration tests.

The email backend is needs to be set in setting.py once in place. Tests use a dummy email backend.
