### ISSUE TITLE
Project owners can invite users to join an approved project.

### ISSUE THREAD

**Issue by tystakartografen** [tystakartografen/cogs3#15]
**Description**
Project owners can invite users to join an approved project.

**Comment by rantahar** [comment]
I'm working on this at the moment. I'm adding an 'invite user' form.

The idea then is that the user can accept or decline the invitation in the memberships view.  I'm adding a boolean field called 'initiated_by_user' to CustomUser to facilitate this.

Any comments?

**Comment by tystakartografen** [comment]
Ideally, the CustomUser model should only contain the necessary fields to represent a user. I would recommend putting any fields related to a project membership invite, either the project membership model or even create a project membership invite model. How would the `initiated_by_user` be used?

**Comment by rantahar** [comment]
I'm sorry, I meant the ProjectUserMembership, not CustomUser.

The memberships view would allow the user to accept the membership if Initiated_by_user is false and similarly the requests view would allow the tech lead to accept if initiated_by_user is true. The permissions to edit the membership status would similarly depend on the field.

The user/tech_lead could of course decline the invitation/request as well. Once the invitation/request is accepted, the only the tech lead could revoke or suspend.

**Comment by tystakartografen** [comment]
That sounds good to me :). It's probably worth adding a help text entry to the field to clarify it's purpose.

**Comment by rantahar** [comment]
Added pull request #46 that implements inviting members.

Note that there is a weird bug that causes the integration test to fail in my setup. Updating the membership status does not work in the memberships view. The bug only applies to the integration test.

Currently the tech lead can only add existing users. We should probably add a way to instantiate users with institutional addresses automatically when invited to a project.
