### ISSUE TITLE
Date picker uses different date format to date field

### ISSUE THREAD

**Issue by edbennett** [tystakartografen/cogs3#21]
In the project request form, the Start date and End date fields use the jQuery date picker, which outputs a date in the MM/DD/YYYY format. However, the model expects a date in the format DD/MM/YYYY, so valid dates are stored incorrectly 40% of the time and are rejected 60% of the time. Either the jQuery widget should be told to use the DD/MM/YYYY format, or both the widget and the model should standardise on ISO 8601 (YYYY-MM-DD).

**Comment by tystakartografen** [comment]
Good spot, I will review / fix the issue.

**Comment by tystakartografen** [comment]
Project date fields now use 'YYYY-MM-DD' format see https://github.com/tystakartografen/cogs3/commit/03e8dacfc134456a6b85fb5508230f7584ab92f9. 

**Project application view**

![screen shot 2018-05-16 at 10 27 45](https://user-images.githubusercontent.com/12101684/40109085-869563d0-58f4-11e8-809d-15a295923935.png)

**Project admin view**
![screen shot 2018-05-16 at 10 28 06](https://user-images.githubusercontent.com/12101684/40109091-89fc8e18-58f4-11e8-8e68-7b332ac20c5c.png)

If you are satisfied with this fix, let me know and I will merge it into the master branch.

**Comment by edbennett** [comment]
I'm a big fan of ISO 8601, so I'm very happy with this fix :)

**Comment by tystakartografen** [comment]
https://github.com/tystakartografen/cogs3/pull/23 Merged datepicker-fix into master.
