### ISSUE TITLE
Unhandled error 500 when creating projects with duplicate titles

### ISSUE THREAD

**Issue by M4rkD** [tystakartografen/cogs3#30]
Creating a project with a title which exists in the database violates the unique key constraint. This is unhandled and returns with code 500.

**Comment by tystakartografen** [comment]
Unable to reproduce the error on the master branch. I have added a unit test to verify that two projects can have the same title (https://github.com/tystakartografen/cogs3/commit/d18da4afe8f2df00b20fcab61cc58f57050d12cd). 

Also, I have updated the two projects on the dev server to have the same title. 

It might be worth checking that your migrations are up to date? `python manage.py migrate`. 

If the issue persists, attach your project creation code.

**Comment by M4rkD** [comment]
Fixed in current master
