### ISSUE TITLE
Only one project can be in an awaiting approval state at a time

### ISSUE THREAD

**Issue by M4rkD** [tystakartografen/cogs3#31]
Attempting to create a new projects while there is another project in an awaiting approval state, violates the unique key constraint on project code (since both are null).

**Comment by tystakartografen** [comment]
Similar to #30, unable to reproduce this error on the master branch. 

The unit tests added in https://github.com/tystakartografen/cogs3/commit/d18da4afe8f2df00b20fcab61cc58f57050d12cd set both projects status to 'Awaiting Approval'.

It might be worth checking that your migrations are up to date? `python manage.py migrate`. 

If the issue persists, attach your project creation code.

**Comment by M4rkD** [comment]
Fixed in current master
