### ISSUE TITLE
Allocation storage detail not shown in project view

### ISSUE THREAD

**Issue by M4rkD** [tystakartografen/cogs3#32]
Allocation storage is a field on the database which is not populated by the project form, but displayed in a single project view. The form instead requests "Home storage in GB" and "Scratch storage in GB", which I believe should be displayed in the project view instead.

**Comment by tystakartografen** [comment]
There was a recent update to the project detail view ea468573fd0eb31d92029866ca14c59fa096f8e4, it now displays the "Home storage in GB" and "Scratch storage in GB".

Current headings that are displayed in the project detail view on the master branch. 

<img width="243" alt="screen shot 2018-05-22 at 20 39 22" src="https://user-images.githubusercontent.com/12101684/40385950-3f06593c-5e00-11e8-935b-bbd0e041f24a.png">
