### ISSUE TITLE
ARCCA displayed for Swansea users

### ISSUE THREAD

**Issue by M4rkD** [tystakartografen/cogs3#34]
The ARCCA textbox is displayed for all users. I suspect that Swansea users would not know what this is.

Since the system goes live for Cardiff only first, then this is not an immediate concern, but I believe this should be addressed before Swansea goes live.

**Comment by tystakartografen** [comment]
Good spot, needs fixing.

**Comment by tystakartografen** [comment]
Pending merge of #51
